<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 24/07/2018
 * Time: 11:45
 */

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\UploadForm;
use yii\web\UploadedFile;


class UploadController extends Controller
{
    public function actionUpload()
    {
        $model = new UploadForm();

        if (Yii::$app->request->isPost) {

            $model->images = UploadedFile::getInstance($model, 'image');
            if ($model->upload()) {
                // file is uploaded successfully
                $command = Yii::$app->db->createCommand(
                    "INSERT INTO upload_form(image) VALUES(:image)"
                );
                $command->bindValue(':image', 'upload/' . $model->images->baseName . '.' . $model->images->extension);
                $sql_result = $command->execute();
//                return;
            }
        }
        return $this->render('upload', ['model' => $model]);
    }

    public function actionIndex()
    {
        $query=UploadForm::find()->select('image')->all();
        //var_dump($query);die();
        $result=UploadForm::find()->select('image')->one();
        //var_dump($result);die();
        return $this->render('index', ['query' => $query, 'result' => $result]);
    }
    public function actionUpsert()
    {
        return parent::actions(); // TODO: Change the autogenerated stub
    }
}
